server:
  port: 9001
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
  # 需要指明spring.application.name,这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name,name 和client1里的name一致
    name: consumer